name: "PR Title Check"
on:
  pull_request:
    types: [closed]

jobs:
  title-check:
    name: excute-test-cases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Check PR title for execution
        run: |
          if contains(github.event.pull_request.title, 'execute=true'); then
            # Your workflow steps here
            echo "The PR title contains 'execute=true'. Triggering actions..."
          elif contains(github.event.pull_request.title, 'execute=false'); then
            echo "The PR title contains 'execute=false'. Failing workflow..."
            exit 1
          else
            echo "The PR title doesn't contain 'execute=true' or 'execute=false'. Failing workflow..."
            exit 1
          fi
        shell: bash
