name: "PR Title Checks"
on:
  pull_request:
    types: [closed]

jobs:
  title-check:
    name: excute-test-cases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Check PR title for execution
        if: contains(github.event.pull_request.title, 'execute=true')
        run: |
          # Your workflow steps here
          echo "The PR title contains 'execute=true'. Triggering actions..."
 
      - name: Fail if PR title contains 'execute=false'
        if: contains(github.event.pull_request.title, 'execute=false')
        run: |
          echo "The PR title contains 'execute=false'. Failing workflow..."
          exit 1
 
      - name: Fail if PR title does not contain 'execute=true' or 'execute=false'
        if: "!contains(github.event.pull_request.title, 'execute=true') && !contains(github.event.pull_request.title, 'execute=false')"
        run: |
          echo "The PR title doesn't contain 'execute=true' or 'execute=false'. Failing workflow..."
          exit 1
          
